import json, re, os

with open('C:/Users/admin/Documents/GitHub/namesilo-evidence/docs/namesilo-scan.html','rb') as f:
    scan = f.read().decode('utf-8','replace')
style_block = re.search(r'<style>.*?</style>', scan, re.DOTALL).group()

with open('C:/Users/admin/Documents/GitHub/namesilo-evidence/pkg/evidence/pg_criminal_domains.json') as f:
    data = json.load(f)
data_str = json.dumps(data, separators=(',',':'))

brands = [('USPS',75),('Google',48),('Telegram',14),('Solana',9),('Facebook',8),('Apple',8),('WhatsApp',7),('Steam',6),('IRS',5),('Roblox',5),('Instagram',4),('Amazon',3)]
brand_html = ''.join('<div class="brand-card"><span class="bc-name">%s</span><span class="bc-count">%d</span></div>' % (b,c) for b,c in brands)

tld_rows = ''
for tld,count,pct,cls in [('.com',43052,100,''),('.top',26614,61.8,'rd'),('.net',15412,35.8,''),('.sbs',12013,27.9,'or'),('.org',11035,25.6,''),('.biz',6974,16.2,'rd'),('.wiki',6597,15.3,''),('.info',5686,13.2,''),('.cfd',5359,12.5,'or'),('.xyz',5248,12.2,'')]:
    bc = ' '+cls if cls else ''
    tld_rows += '<tr><td>%s</td><td class="nr">%s</td><td><div class="bar%s"><span style="width:%s%%"></span></div></td></tr>' % (tld, '{:,}'.format(count), bc, pct)

src_tags = ''
for s,col in zip(['Spamhaus DBL','SURBL','HaGeZi TIF','1Hosts Xtra','ScamAdviser','PhishingArmy','CERT-PL','VirusTotal','AlienVault OTX','PhishTank','AdGuard SDNS','StevenBlack','URLhaus','Google Safe Browsing','ThreatFox','malware-filter','blocklistproject','PhishingDB','URIBL','DNSBL','PhishStats','OpenPhish','URLScan','PhishDestroy Internal'],['rd','rd','or','or']+['nt']*20):
    src_tags += '<span class="b %s">%s</span>' % (col, s)

js = (
'<script>'
'const DATA=__DATA__;'
'const PAGE=100;var cur=0,filtered=DATA;'
'function doFilter(){'
'var s=document.getElementById("srch").value.toLowerCase();'
'var c=document.getElementById("catF").value;'
'filtered=DATA.filter(function(r){'
'if(s&&r[0].indexOf(s)<0&&r[3].toLowerCase().indexOf(s)<0)return false;'
'if(c==="hard"&&r[1]!=="hard")return false;'
'if(c==="listed"&&r[1]!=="listed")return false;'
'if(c==="brand"&&!r[3])return false;'
'return true;});cur=0;render();}'
'function mkRow(r,idx){'
'var tr=document.createElement("tr");'
'var tdN=document.createElement("td");tdN.style.cssText="opacity:.4;font-size:11px";tdN.textContent=String(cur+idx+1);tr.appendChild(tdN);'
'var tdF=document.createElement("td");'
'var fav=document.createElement("img");'
'fav.src="https://favicon.im/"+r[0]+"?larger=false";'
'fav.width=16;fav.height=16;fav.style.cssText="vertical-align:middle;border-radius:2px";'
'fav.onerror=function(){this.src="https://www.google.com/s2/favicons?domain="+r[0]+"&sz=16";this.onerror=function(){this.style.opacity=".1";};};'
'tdF.appendChild(fav);tr.appendChild(tdF);'
'var tdD=document.createElement("td");'
'var a=document.createElement("a");a.href="http://"+r[0];a.target="_blank";a.rel="noopener noreferrer";a.style.color="var(--cy)";a.textContent=r[0];'
'tdD.appendChild(a);tr.appendChild(tdD);'
'var tdS=document.createElement("td");'
'var sp=document.createElement("span");sp.className="b "+(r[1]==="hard"?"hard":"listed");sp.textContent=r[1]==="hard"?"hard":"listed";'
'tdS.appendChild(sp);tr.appendChild(tdS);'
'var tdC=document.createElement("td");tdC.className="nr";tdC.textContent=String(r[2]);tr.appendChild(tdC);'
'var tdB=document.createElement("td");'
'if(r[3]){var sb=document.createElement("span");sb.className="b rd";sb.textContent=r[3];tdB.appendChild(sb);}'
'tr.appendChild(tdB);return tr;}'
'function render(){'
'var tb=document.getElementById("tbody");tb.textContent="";'
'var chunk=filtered.slice(cur,cur+PAGE);'
'for(var i=0;i<chunk.length;i++)tb.appendChild(mkRow(chunk[i],i));'
'document.getElementById("cnt").textContent=filtered.length.toLocaleString()+" domains";'
'renderPager();}'
'function renderPager(){'
'var pages=Math.ceil(filtered.length/PAGE);'
'var p=document.getElementById("pager");p.textContent="";'
'if(pages<=1)return;'
'var pg=Math.floor(cur/PAGE);'
'var start=Math.max(0,pg-2),end=Math.min(pages-1,pg+2);'
'function mkBtn(label,n,active){'
'var b=document.createElement("button");b.textContent=label;'
'if(active)b.style.cssText="background:rgba(0,200,255,.2);border-color:rgba(0,200,255,.4)";'
'b.onclick=function(){go(n);};p.appendChild(b);p.appendChild(document.createTextNode(" "));}'
'if(pg>0)mkBtn("< Prev",(pg-1)*PAGE,false);'
'for(var i=start;i<=end;i++)mkBtn(String(i+1),i*PAGE,i===pg);'
'if(pg<pages-1)mkBtn("Next >",(pg+1)*PAGE,false);}'
'function go(n){cur=n;render();window.scrollTo(0,document.getElementById("domains").offsetTop-60);}'
'doFilter();'
'var _ro=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){e.target.classList.add("in");_ro.unobserve(e.target);}});},{threshold:0.07,rootMargin:"0px 0px -32px 0px"});'
'document.querySelectorAll(".reveal").forEach(function(el){_ro.observe(el);});'
'</script>'
)

page = (
'<!DOCTYPE html><html lang="en"><head>'
'<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">'
'<meta name="robots" content="index, follow">'
'<meta name="description" content="183,419 NameSilo domains confirmed malicious across 25+ threat feeds. 109,196 hard-confirmed. 201 brand impersonations: USPS, Google, Telegram, Apple, IRS.">'
'<meta name="keywords" content="PrivacyGuardian,NameSilo abuse,malicious domains,phishing,blocklist,brand impersonation,threat intelligence">'
'<title>PrivacyGuardian Shield &#8212; 183,419 Malicious NameSilo Domains | PhishDestroy</title>'
'<meta property="og:type" content="article">'
'<meta property="og:site_name" content="PhishDestroy">'
'<meta property="og:url" content="https://phishdestroy.github.io/namesilo-evidence/namesilo-privacyguardian.html">'
'<meta property="og:title" content="PrivacyGuardian Shield &#8212; 183,419 Malicious NameSilo Domains">'
'<meta property="og:description" content="183,419 NameSilo domains confirmed malicious. NameSilo owns both the registrar and the privacy service shielding the operators.">'
'<meta property="og:image" content="https://phishdestroy.eth.limo/namesilo-og.png">'
'<meta name="twitter:card" content="summary_large_image">'
'<meta name="twitter:title" content="PrivacyGuardian Shield &#8212; 183,419 Malicious NameSilo Domains">'
'<meta name="twitter:description" content="183,419 NameSilo domains confirmed malicious. NameSilo owns the registrar AND the privacy shield.">'
'<link rel="canonical" href="https://phishdestroy.github.io/namesilo-evidence/namesilo-privacyguardian.html">'
+ style_block +
'<style>'
'.pg-hero{background:linear-gradient(135deg,rgba(255,60,60,.08),rgba(200,0,0,.04));border:1px solid rgba(255,60,60,.25);border-radius:10px;padding:28px 32px;margin-bottom:32px}'
'.pg-stat{display:inline-block;margin:8px 20px 8px 0;text-align:center}'
'.pg-stat strong{display:block;font-size:2rem;color:#f55}'
'.pg-stat span{font-size:12px;opacity:.65;text-transform:uppercase;letter-spacing:.05em}'
'.brand-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:8px;margin:16px 0}'
'.brand-card{background:rgba(255,255,255,.04);border:1px solid rgba(255,255,255,.08);border-radius:6px;padding:10px 14px;display:flex;justify-content:space-between;align-items:center}'
'.bc-name{font-weight:600;font-size:13px}'
'.bc-count{font-size:20px;font-weight:700;color:#f55}'
'.filter-bar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px;align-items:center}'
'.filter-bar input{flex:1;min-width:200px;background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.15);color:inherit;padding:8px 12px;border-radius:6px;font-size:13px}'
'.filter-bar select{background:rgba(255,255,255,.07);border:1px solid rgba(255,255,255,.15);color:inherit;padding:8px 10px;border-radius:6px;font-size:13px}'
'.b.hard{background:rgba(255,60,60,.18);color:#f88}'
'.b.listed{background:rgba(255,160,0,.15);color:#fba}'
'</style></head><body>'
'<header><nav>'
'<a href="namesilo-scan.html">&#8592; Report</a> &nbsp;&middot;&nbsp; '
'<a href="namesilo-clusters.html">Clusters</a> &nbsp;&middot;&nbsp; '
'<a href="namesilo-domains.html">107k IOCs</a> &nbsp;&middot;&nbsp; '
'<strong>PrivacyGuardian Shield</strong>'
'</nav></header>'
'<main style="max-width:1200px;margin:0 auto;padding:20px">'
'<h1 style="margin-bottom:4px">PrivacyGuardian Shield</h1>'
'<p style="opacity:.6;margin-top:0;margin-bottom:24px">183,419 NameSilo-registered malicious domains hidden behind NameSilo&#39;s own WHOIS privacy service</p>'
'<div class="pg-hero">'
'<div class="pg-stat"><strong>183,419</strong><span>Total malicious</span></div>'
'<div class="pg-stat"><strong>109,196</strong><span>Hard confirmed</span></div>'
'<div class="pg-stat"><strong>19,874</strong><span>3+ sources</span></div>'
'<div class="pg-stat"><strong>201</strong><span>Brand impersonations</span></div>'
'<div class="pg-stat"><strong>25+</strong><span>Intel sources</span></div>'
'<p style="margin:16px 0 0;font-size:13px;opacity:.8">All domains registered with <strong>NameSilo, Inc.</strong> and using <strong>PrivacyGuardian.org</strong> WHOIS privacy &#8212; a service also owned and operated by NameSilo. The registrar owns the registration, the privacy shield, and collects revenue on both.</p>'
'</div>'
'<div class="panel reveal"><h2>Brand Impersonations &#8212; 201 Domains</h2>'
'<p style="opacity:.7;font-size:13px">Confirmed domains impersonating known brands, all PrivacyGuardian-shielded on NameSilo.</p>'
'<div class="brand-grid">' + brand_html + '</div></div>'
'<div class="panel reveal" style="margin-top:24px"><h2>Top TLDs</h2>'
'<table><thead><tr><th>TLD</th><th class="nr">Count</th><th style="width:200px">Scale</th></tr></thead>'
'<tbody>' + tld_rows + '</tbody></table></div>'
'<div class="panel reveal" style="margin-top:24px"><h2>Intelligence Sources</h2>'
'<p style="font-size:13px;opacity:.7">Verified against 25+ independent threat feeds via RDAP validation against NameSilo registration API.</p>'
'<div style="display:flex;flex-wrap:wrap;gap:6px;margin-top:12px">' + src_tags + '</div></div>'
'<div class="panel reveal" style="margin-top:24px">'
'<h2 id="domains">Full Domain List &#8212; 183,419 Entries</h2>'
'<div class="filter-bar">'
'<input type="text" id="srch" placeholder="Search domain or brand..." oninput="doFilter()">'
'<select id="catF" onchange="doFilter()">'
'<option value="">All</option>'
'<option value="hard">Hard confirmed (109k)</option>'
'<option value="listed">Listed (74k)</option>'
'<option value="brand">Brand impersonation (201)</option>'
'</select>'
'<span id="cnt" style="font-size:13px;opacity:.6"></span>'
'</div>'
'<div style="overflow-x:auto">'
'<table><thead><tr>'
'<th style="width:40px">#</th>'
'<th style="width:24px"></th>'
'<th>Domain</th>'
'<th>Status</th>'
'<th class="nr">Sources</th>'
'<th>Brand</th>'
'</tr></thead><tbody id="tbody"></tbody></table></div>'
'<div class="pager" id="pager"></div></div>'
'<div style="text-align:center;padding:20px 0 12px;font-size:13px;opacity:.6">'
'<a href="https://phishdestroy.eth.limo" target="_blank" rel="noopener" style="color:var(--cy,#0cf)">&#9657; phishdestroy.eth.limo</a>'
' &nbsp;&middot;&nbsp; <a href="namesilo-scan.html" style="color:var(--cy,#0cf)">Investigation Report</a>'
' &nbsp;&middot;&nbsp; <a href="namesilo-domains.html" style="color:var(--cy,#0cf)">107k Zone Scan IOCs</a>'
'</div></main>'
+ js +
'</body></html>'
)

page = page.replace('__DATA__', data_str)

outpath = 'C:/Users/admin/Documents/GitHub/namesilo-evidence/docs/namesilo-privacyguardian.html'
with open(outpath,'wb') as f:
    f.write(page.encode('utf-8'))
sz = os.path.getsize(outpath)
print('Done: %dMB (%d bytes)' % (sz//1024//1024, sz))
