#!/usr/bin/env python3
"""Build ioc/ feeds from data/ioc/ outputs.

The lists are cumulative: brand/serial classification is merged with the
persisted feed cross-reference sources and with whatever is already published.
A rebuild may only add entries, never drop them — an earlier version rewrote
the lists from brand/serial data alone and silently discarded ~196k domains
that came from the feed cross-reference.
"""

import json, csv, io
from pathlib import Path
from datetime import date

DATA_IOC = Path("data/ioc")
IOC_DIR  = Path("ioc")
IOC_DIR.mkdir(exist_ok=True)
TODAY = date.today().isoformat()


def read_list(path):
    """Domains from a blocklist file, ignoring the '#' header and blank lines."""
    if not path.exists():
        return set()
    out = set()
    for line in path.read_text(encoding="utf-8", errors="replace").splitlines():
        line = line.strip().lower()
        if line and not line.startswith("#"):
            out.add(line)
    return out


brand_file = DATA_IOC / "brand_domains.json"
brand_data = json.loads(brand_file.read_text(encoding="utf-8")) if brand_file.exists() else {}
brand_doms = {d.lower() for doms in brand_data.get("keywords", {}).values() for d in doms}

serial_file = DATA_IOC / "serial_registrants.json"
serial_data = json.loads(serial_file.read_text(encoding="utf-8")) if serial_file.exists() else {}
serial_doms = {
    d.lower() for reg in serial_data.get("registrants", [])
    if reg.get("count", 0) >= 10
    for d in reg.get("domains", [])
}

# Persisted feed / intel cross-reference results plus the already published lists.
feed_high      = read_list(DATA_IOC / "feed_high.txt")
feed_confirmed = read_list(DATA_IOC / "feed_confirmed.txt") | read_list(DATA_IOC / "intel_confirmed.txt")
published_high = read_list(IOC_DIR / "domains_high.txt")
published_all  = read_list(IOC_DIR / "domains_all_malicious.txt")

high_doms = brand_doms | feed_high | published_high
all_doms  = high_doms | serial_doms | feed_confirmed | published_all


def write_blocklist(path, title, doms):
    header = "# " + title + " - Generated by PhishDestroy - " + TODAY + " - " + str(len(doms)) + " entries"
    path.write_text(header + chr(10) + chr(10).join(sorted(doms)) + chr(10), encoding="utf-8")


write_blocklist(IOC_DIR / "domains_high.txt",
    "NameSilo (IANA #1479) high-severity malicious domains", high_doms)
write_blocklist(IOC_DIR / "domains_all_malicious.txt",
    "NameSilo (IANA #1479) all malicious domains", all_doms)

# ── indicators.csv — also cumulative; existing rows keep their source labels ──
COLS = ["domain", "category", "severity", "threat_sources"]
csv_path = IOC_DIR / "indicators.csv"
existing = {}
if csv_path.exists():
    with csv_path.open(encoding="utf-8-sig", errors="replace", newline="") as fh:
        for r in csv.DictReader(fh):
            d = (r.get("domain") or "").strip().lower()
            if d:
                existing[d] = {c: (r.get(c) or "") for c in COLS}
                existing[d]["domain"] = d

for d in sorted(all_doms):
    if d in existing:
        continue
    if d in brand_doms:
        existing[d] = {"domain": d, "category": "PHISHING", "severity": "3",
                       "threat_sources": "brand-imitation"}
    elif d in high_doms:
        existing[d] = {"domain": d, "category": "PHISHING", "severity": "3",
                       "threat_sources": "feed-crossref"}
    elif d in serial_doms:
        existing[d] = {"domain": d, "category": "SUSPICIOUS", "severity": "2",
                       "threat_sources": "serial-registrant"}
    else:
        existing[d] = {"domain": d, "category": "SUSPICIOUS", "severity": "2",
                       "threat_sources": "feed-crossref"}


def _sev(row):
    try:
        return int(row.get("severity") or 0)
    except ValueError:
        return 0


buf = io.StringIO()
w = csv.DictWriter(buf, fieldnames=COLS, extrasaction="ignore")
w.writeheader()
for d in sorted(existing, key=lambda x: (-_sev(existing[x]), x)):
    w.writerow(existing[d])
csv_path.write_text(buf.getvalue(), encoding="utf-8-sig")

# Keep the GitHub Pages copies in sync so the published feeds never lag behind.
docs_ioc = Path("docs/ioc")
if docs_ioc.is_dir():
    for name in ("domains_high.txt", "domains_all_malicious.txt", "indicators.csv"):
        src = IOC_DIR / name
        if src.exists():
            (docs_ioc / name).write_bytes(src.read_bytes())

print("[+] HIGH:", len(high_doms), "ALL:", len(all_doms), "CSV:", len(existing))
