#!/usr/bin/env python3
"""Build ioc/ feeds from data/ioc/ outputs (brand domains + serial registrants)."""

import json, csv, io
from pathlib import Path
from datetime import date

DATA_IOC = Path("data/ioc")
IOC_DIR  = Path("ioc")
IOC_DIR.mkdir(exist_ok=True)
TODAY = date.today().isoformat()

brand_file = DATA_IOC / "brand_domains.json"
brand_data  = json.loads(brand_file.read_text(encoding="utf-8")) if brand_file.exists() else {}
brand_doms  = sorted({d for doms in brand_data.get("keywords", {}).values() for d in doms})

serial_file = DATA_IOC / "serial_registrants.json"
serial_data = json.loads(serial_file.read_text(encoding="utf-8")) if serial_file.exists() else {}
serial_doms = sorted({
    d for reg in serial_data.get("registrants", [])
    if reg.get("count", 0) >= 10
    for d in reg.get("domains", [])
})

all_doms = sorted(set(brand_doms) | set(serial_doms))

header_high = "# NameSilo (IANA #1479) - brand-imitation domains (keyword match)
"
header_high += "# Generated by PhishDestroy - " + TODAY + "
"
header_high += "# " + str(len(brand_doms)) + " entries

"
(IOC_DIR / "domains_high.txt").write_text(header_high + "
".join(brand_doms) + "
", encoding="utf-8")

header_all = "# NameSilo (IANA #1479) - brand-imitation + serial-registrant domains
"
header_all += "# Generated by PhishDestroy - " + TODAY + "
"
header_all += "# " + str(len(all_doms)) + " entries

"
(IOC_DIR / "domains_all_malicious.txt").write_text(header_all + "
".join(all_doms) + "
", encoding="utf-8")

COLS = ["domain", "category", "severity", "threat_sources"]
rows = [{"domain": d, "category": "PHISHING", "severity": "3", "threat_sources": "brand-imitation"} for d in brand_doms]
rows += [{"domain": d, "category": "SUSPICIOUS", "severity": "2", "threat_sources": "serial-registrant"} for d in set(serial_doms) - set(brand_doms)]
rows.sort(key=lambda x: -int(x["severity"]))

buf = io.StringIO()
w = csv.DictWriter(buf, fieldnames=COLS)
w.writeheader()
w.writerows(rows)
(IOC_DIR / "indicators.csv").write_text(buf.getvalue(), encoding="utf-8-sig")

print("[+] HIGH (brand):", len(brand_doms), " ALL:", len(all_doms), " indicators:", len(rows))
