#!/usr/bin/env python3
"""Build ioc/ feeds from data/ioc/ outputs (brand domains + serial registrants).
Used for namesilo-evidence where the full HTTP/classify pipeline has not run."""

import json, csv
from pathlib import Path

DATA_IOC  = Path("data/ioc")
IOC_DIR   = Path("ioc")
IOC_DIR.mkdir(exist_ok=True)

# ── Load brand-keyword matched domains ────────────────────────────────────────
brand_file = DATA_IOC / "brand_domains.json"
brand_data  = json.loads(brand_file.read_text(encoding="utf-8")) if brand_file.exists() else {}
brand_doms  = sorted({d for doms in brand_data.get("keywords", {}).values() for d in doms})

# ── Load serial-registrant domains (≥10 domains per email) ───────────────────
serial_file = DATA_IOC / "serial_registrants.json"
serial_data = json.loads(serial_file.read_text(encoding="utf-8")) if serial_file.exists() else {}
serial_doms = sorted({
    d for reg in serial_data.get("registrants", [])
    if reg.get("count", 0) >= 10
    for d in reg.get("domains", [])
})

# HIGH = brand keyword imitation (strong abuse signal)
# ALL  = brand + serial (broader)
high_doms = brand_doms
all_doms  = sorted(set(brand_doms) | set(serial_doms))

today = __import__("datetime").date.today().isoformat()

(IOC_DIR / "domains_high.txt").write_text(
    f"# NameSilo (IANA #1479) — brand-imitation domains (keyword match)
"
    f"# Generated by PhishDestroy — {today}
"
    f"# {len(high_doms)} entries

" +
    "
".join(high_doms) + "
",
    encoding="utf-8"
)

(IOC_DIR / "domains_all_malicious.txt").write_text(
    f"# NameSilo (IANA #1479) — brand-imitation + serial-registrant domains
"
    f"# Generated by PhishDestroy — {today}
"
    f"# {len(all_doms)} entries

" +
    "
".join(all_doms) + "
",
    encoding="utf-8"
)

# SIEM CSV
COLS = ["domain", "category", "severity", "threat_sources"]
rows = [{"domain": d, "category": "PHISHING", "severity": "3", "threat_sources": "brand-imitation"} for d in brand_doms]
rows += [{"domain": d, "category": "SUSPICIOUS", "severity": "2", "threat_sources": "serial-registrant"} for d in set(serial_doms) - set(brand_doms)]
rows.sort(key=lambda x: -int(x["severity"]))

import io
buf = io.StringIO()
w = csv.DictWriter(buf, fieldnames=COLS)
w.writeheader()
w.writerows(rows)
(IOC_DIR / "indicators.csv").write_text(buf.getvalue(), encoding="utf-8-sig")

print(f"[+] HIGH (brand): {len(high_doms):,}  ALL: {len(all_doms):,}  indicators: {len(rows):,}")
print(f"    ioc/domains_high.txt         — {len(high_doms):,}")
print(f"    ioc/domains_all_malicious.txt — {len(all_doms):,}")
print(f"    ioc/indicators.csv            — {len(rows):,}")

if __name__ == "__main__":
    pass
